---
layout:  post
title: "Agents of Neoliberal Globalization Now in Print!"
comments:  true
published: true
author: "Derek Darves"
date: 2016-07-24 08:00:00
categories: ['Book']
output:
  html_document:
    mathjax:  default
    fig_caption:  true
---
	
	
```{r include = FALSE}

library(knitr)

```

After many years of hard work I'm thrilled to announce that the collaborative research project  Michael Dreiling and I began in 2000 has been published with [Cambridge University Press!](http://www.cambridge.org/pw/academic/subjects/sociology/political-sociology/agents-neoliberal-globalization-corporate-networks-state-structures-and-trade-policy?format=HB) Our book, *Agents of Neoliberal Globalization* can be purchased directly from Amazon, or with a discount using the [promotional code in this flyer](http://derekyves.github.io/images/Agents_Neoliberal_Globalization_Flyer.pdf). Many thanks to the editors, reviewers, and friends who helped improve this book over many years and many drafts. Our thanks, also, to Athena Llewellyn, Creative Director of the [Barat Foundation](http://baratfoundation.org), for creating the excellent cover art! 

At a time when trade policies like the TPP have emerged as a topic of major national and global interest, we hope that our work will inform public debate about the drivers of globalization and, looking ahead, the kinds of economic policies that will best support a more sustainable and peaceful future. The publisher's summary follows:

<hr>
*Depictions of globalization commonly recite a story of a market unleashed, bringing Big Macs and iPhones to all corners of the world. Human society appears as a passive observer to a busy revolution of an invisible global market, paradoxically unfolding by its own energy. Sometimes, this market is thought to be unleashed by politicians working on the surface of an autonomous state. This book rejects both perspectives and provides an analytically rich alternative to conventional approaches to globalization. By the 1980s, an enduring corporate coalition advanced in nearly synonymous terms free trade, tax cuts, and deregulation. Highly networked corporate leaders and state officials worked in concert to produce the trade policy framework for neoliberal globalization. Marshaling original network data and a historical narrative, this book shows that the globalizing corporate titans of the late 1960s aligned with economic conservatives to set into motion this vision of a global free market.*
<hr>

